### ISSUE TITLE
About Alibaba Trace Network Traffic Reply

### ISSUE THREAD

**Issue by lastweek** [mblo/hire-cluster-simulator#2]
Hi there,

Thank you for releasing the code and I really enjoyed reading your paper.

While reading the Eval section, I found myself a bit confused on how you guys managed to replay the Alibaba trace. In particular, how do you schedule jobs and calculate the network traffic. Are you using the (net_in and net_out) [here](https://github.com/alibaba/clusterdata/blob/master/cluster-trace-v2018/schema.txt)?

Ultimately, I want to learn whether it is possible to calculate each machine's (and switch's) network utilization over a timeline (suppose each machine has multiple containers).

Can you tell me more about it? Looking forward to your reply. Thank you!

**Comment by mblo** [comment]
Hi,

Sorry for the late response - I must have somehow missed this issue.

Your pointer to the trace is correct; there is some information given about the network usage (in/out traffic) of a machine/container. However, there is no information given on the communication pattern of the containers/machines. 

For example, if the trace contains three containers (A,B,C) that belong to the same application group, the trace gives only infos on in/out network traffic of these containers, but not how these containers communicate. The network traffic of A could be only between A and B, or maybe between A and any other container but not B and C.
This is why we did not consider the network usage of the trace in our simulations. 

So regarding your second question ("whether it is possible to calculate each machine's (and switch's) network utilization"),
I have to say no -- because it is currently not part of the simulation.

Hope that answers your question.
